### ISSUE TITLE
Compatible with Objective C.

### ISSUE THREAD

**Issue by ambujshukla-cdn** [crowdconnected/colocator-ios-swift-3.1#1]
Hi, 
Is this library work using XCode 9. As it is giving compiler error the current version of Swift.
Error:- Module compiled with Swift 3.0.1 cannot be imported in Swift 3.1:.

"Please give anwer this that this library have support of Objective C or not"

As it is saying in the Colocator  developer console that the path for the CClocation is this:-$(SRCROOT)/Carthage/Build/iOS/CCLocation.framework but this CCLocation framework comes under Carthage>Checkouts>colocator-ios-swift-3.0.1.

Please have a look.

**Comment by kernchen** [comment]
@ambujshukla-cdn, indeed this repository will not support normal XCode 9 as it comes with Swift 3.2 and 4. For use in Xcode 9, please refer to the colocator-ios-swift-3.2 repository. If you do this, could you please let me know, if you experience any issues there?

We had some major library reworks for version 2 and only recently switched to a method to provide the Swift 3.0.1, Swift 3.1 and Swift 3.2 libraries via separate repositories. Please note that for the pods, you also have to use CCLocation-3.2 with the according version tag.

**Comment by ambujshukla-cdn** [comment]
Hi Kernchen,
I have used this for cocoapod "pod 'CCLocation-Swift-3.1'" which is not installing the 3.2 version:-
Downloading dependencies
Installing CCLocation-Swift-3.2 (1.9.9)
Installing CocoaLumberjack (3.2.1)
Installing ReSwift (4.0.0)
Installing Result (3.2.4)
Installing SocketRocket (0.4.2)
Installing SwiftProtobuf (0.9.905)
Installing TrueTime (4.1.4)
[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pods being used are: CocoaLumberjack, ReSwift, Result, SwiftProtobuf, and TrueTime

**Comment by ambujshukla-cdn** [comment]
Hi Kernchen,
Did you able to replicate the issue or come in to any conclusion for integrating the library via pod?

**Comment by kernchen** [comment]
Hi @ambujshukla-cdn, 

Not yet, since I was travelling last few days, I'll get back to you asap.

**Comment by kernchen** [comment]
Hi @ambujshukla-cdn, I was able to do a quick test of an example Carthage integration first with an Objective C based example project using the colocator-ios-swift-3.2 library repository and Xcode version 9.0. I am not experiencing any issue with Carthage in this combination.

Did you try something similar to the above mentioned? If the above didn't work for you, it would be worth to somehow compare the Xcode projects.

I will also still try to test the Cocoapod version to also see if this option can work.

**Comment by kernchen** [comment]
Also just created an Objective C project from scratch in Xcode 9 using the following Podfile content:

platform :ios, '8.0'
use_frameworks!

target 'CCLocationSampeObjectiveCCocoapods' do
  pod 'CCLocation-Swift-3.2'
end

The only problem I've got was that I had to disable bitcode and then it worked immediately on for a device and the simulator.

Could you try the exact Podfile content and try building in Xcode 9.

**Comment by ambujshukla-cdn** [comment]
Hi @kernchen. 
Ok. I'll do in the same way you had performed the integration and get back to you.

**Comment by kernchen** [comment]
This seems to be resolved, so I am going to close this issue
